from typing import Any, Dict


class NativeSession:
    def __init__(self, name: str) -> None: ...

    @property
    def name(self) -> str: ...

    def request(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...

    def recording(self) -> str: ...


def sessions() -> list[str]: ...


def close_all() -> None: ...


def recording(name: str) -> str: ...
