/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeSession {
  constructor(name: string, recording?: AutomaticRecordingOptions | undefined | null)
  name(): string
  open(options?: OpenOptions | undefined | null): Promise<OpenResult>
  run(options: RunOptions): Promise<OpenResult>
  close(): Promise<void>
  state(): Promise<State>
  text(full?: boolean | undefined | null): Promise<string>
  findLocator(stages: Array<LocatorStage>): Promise<Array<TextMatch>>
  waitLocator(stages: Array<LocatorStage>, not?: boolean | undefined | null, timeoutMs?: number | undefined | null): Promise<void>
  clickLocator(stages: Array<LocatorStage>, button?: number | undefined | null, clicks?: number | undefined | null, timeoutMs?: number | undefined | null): Promise<void>
  highlightLocator(stages: Array<LocatorStage>, timeoutMs?: number | undefined | null): Promise<Array<TextMatch>>
  expectLocator(stages: Array<LocatorStage>, not?: boolean | undefined | null, timeoutMs?: number | undefined | null): Promise<void>
  packedScreen(full?: boolean | undefined | null): Promise<PackedScreen>
  cells(x: number, y: number, w?: number | undefined | null, h?: number | undefined | null): Promise<Array<Cell>>
  getCommand(): Promise<string | null>
  getOutput(): Promise<string | null>
  getExitCode(): Promise<number | null>
  getCwd(): Promise<string | null>
  getCursor(): Promise<Cursor>
  getSize(): Promise<Size>
  getBellCount(): Promise<number>
  getBellEvents(): Promise<Array<BellEvent>>
  write(data: string): Promise<void>
  type(text: string): Promise<void>
  submit(data?: string | undefined | null): Promise<void>
  press(keys: Array<string>): Promise<void>
  keyDown(keys: Array<string>): Promise<void>
  repeat(keys: Array<string>): Promise<void>
  keyUp(keys: Array<string>): Promise<void>
  mouseClick(options?: MouseClickOptions | undefined | null): Promise<void>
  mouseMove(x: number, y: number): Promise<void>
  mouseDown(x: number, y: number, button?: number | undefined | null): Promise<void>
  mouseUp(x: number, y: number, button?: number | undefined | null): Promise<void>
  mouseDrag(x1: number, y1: number, x2: number, y2: number, button?: number | undefined | null): Promise<void>
  mouseScroll(direction: string, amount?: number | undefined | null): Promise<void>
  resize(cols: number, rows: number): Promise<void>
  signal(name: string): Promise<void>
  getTitle(): Promise<string | null>
  waitTitle(text: string, options?: TitleOptions | undefined | null): Promise<void>
  expectTitle(text: string, options?: TitleOptions | undefined | null): Promise<void>
  waitIdle(timeoutMs?: number | undefined | null): Promise<void>
  waitCommand(timeoutMs?: number | undefined | null): Promise<void>
  waitExit(timeoutMs?: number | undefined | null): Promise<void>
  waitReady(timeoutMs?: number | undefined | null): Promise<void>
  waitBell(timeoutMs?: number | undefined | null): Promise<void>
  expectExitCode(code: number, timeoutMs?: number | undefined | null): Promise<void>
  expectOutput(text: string, regex?: boolean | undefined | null): Promise<void>
  expectBellCount(count: number, timeoutMs?: number | undefined | null): Promise<void>
  snapshot(name: string, options?: SnapshotOptions | undefined | null): Promise<SnapshotResult>
  screenshot(options?: ScreenshotOptions | undefined | null): Promise<string>
  startRecording(options: RecordingOptions): Promise<void>
  stopRecording(): Promise<string>
  panicProbe(): Promise<void>
}

export interface AutomaticRecordingOptions {
  mode?: string
  directory?: string
}

export declare const enum Backend {
  Alacritty = 'alacritty',
  Ghostty = 'ghostty',
  Rio = 'rio',
  Xtermjs = 'xtermjs'
}

export interface BellEvent {
  sequence: number
  elapsed_ms: number
}

export interface Cell {
  x: number
  y: number
  char: string
  fg: Color
  bg: Color
  bold: boolean
  dim: boolean
  italic: boolean
  inverse: boolean
  invisible: boolean
  strike: boolean
  blink: boolean
  underline: boolean
  underline_style: UnderlineStyle
  underline_color: Color
}

export declare function closeAll(): Promise<void>

export declare function closeAllSync(): void

export type Color =
  number | string

export interface Cursor {
  x: number
  y: number
}

export interface EffectiveTimeouts {
  text: number
  idle: number
  command: number
  exit: number
  ready: number
}

export interface LocatorStage {
  kind: LocatorStageKind
  direction?: LocatorStageDirection
  text?: string
  regex?: boolean
  full?: boolean
  whitespace?: string
  occurrence?: string
  nth?: number
  style?: LocatorStyle
}

export declare const enum LocatorStageDirection {
  Within = 'within',
  After = 'after',
  Before = 'before'
}

export declare const enum LocatorStageKind {
  Text = 'text',
  Style = 'style'
}

export interface LocatorStyle {
  foreground?: string
  background?: string
  bold?: boolean
  dim?: boolean
  italic?: boolean
  underlineStyle?: string
  underlineColor?: string
  inverse?: boolean
  hidden?: boolean
  strikethrough?: boolean
  blink?: boolean
}

export interface MouseClickOptions {
  x?: number
  y?: number
  onText?: string
  button?: number
  clicks?: number
}

export interface OpenOptions {
  backend?: Backend
  shell?: Shell
  cols?: number
  rows?: number
  cwd?: string
  env?: Array<[string, string]>
  waitReady?: boolean
  restart?: boolean
  profileScrollback?: number
  profileColors?: Array<[string, string]>
  timeouts?: Timeouts
}

export interface OpenResult {
  shell_pid: number | null
  session: string
  ready: boolean
  recording: string
}

/**
 * Private native-owned packed screen snapshot.
 *
 * `utf8` decodes to exactly `rows` newline-delimited logical rows. Trailing
 * spaces and blank rows are retained. UTF-8 byte offsets are not terminal cell
 * offsets when rows contain Unicode graphemes.
 */
export interface PackedScreen {
  /** Logical column count. */
  readonly cols: number
  /** Number of logical rows encoded in `utf8`. */
  readonly rows: number
  /** Detached native-owned UTF-8 bytes. Treat this private snapshot as immutable. */
  readonly utf8: Uint8Array
}

export declare function recording(name: string): Promise<string>

export declare const enum RecordingFormat {
  Apng = 'apng',
  Gif = 'gif',
  Mp4 = 'mp4',
  Cast = 'cast'
}

export interface RecordingOptions {
  path: string
  format?: RecordingFormat
  fps?: number
  speed?: number
  idleTimeLimit?: number
  zoom?: number
}

export interface RunOptions {
  backend?: Backend
  program: string
  args?: Array<string>
  cols?: number
  rows?: number
  cwd?: string
  env?: Array<[string, string]>
  waitReady?: boolean
  restart?: boolean
  profileScrollback?: number
  profileColors?: Array<[string, string]>
  timeouts?: Timeouts
}

export interface ScreenshotOptions {
  full?: boolean
  path?: string
  zoom?: number
}

export declare function sessions(): Promise<Array<string>>

export declare const enum Shell {
  Bash = 'bash',
  Powershell = 'powershell',
  Pwsh = 'pwsh',
  Cmd = 'cmd',
  Fish = 'fish',
  Zsh = 'zsh',
  Xonsh = 'xonsh',
  Elvish = 'elvish',
  Nushell = 'nushell'
}

export interface Size {
  cols: number
  rows: number
}

export interface SnapshotOptions {
  update?: boolean
  includeColors?: boolean
  includeTitle?: boolean
  cwd?: string
}

export declare const enum SnapshotResult {
  Passed = 'passed',
  Written = 'written',
  Updated = 'updated'
}

export interface State {
  session_shell: string | null
  cols: number
  rows: number
  cursor: Cursor
  title: string | null
  cwd: string | null
  last_command: string | null
  last_exit: number | null
  exited: number | null
  ready: boolean
  bell_count: number
  timeouts: EffectiveTimeouts
  text: string
}

export interface TextMatch {
  text: string
  start: TextPosition
  end: TextPosition
  spans: Array<TextSpan>
}

export interface TextPosition {
  row: number
  column: number
}

export interface TextSpan {
  row: number
  start: number
  end: number
}

export interface Timeouts {
  text?: number
  idle?: number
  command?: number
  exit?: number
  ready?: number
}

export interface TitleOptions {
  regex?: boolean
  not?: boolean
  timeoutMs?: number
}

export declare const enum UnderlineStyle {
  None = 'none',
  Single = 'single',
  Double = 'double',
  Curly = 'curly',
  Dotted = 'dotted',
  Dashed = 'dashed'
}
