/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeSession {
  constructor(name: string)
  name(): string
  request(payload: any): Promise<unknown>
}

export declare function closeAll(): Promise<void>

export declare function closeAllSync(): void

export declare function recording(name: string): Promise<string>

export declare function sessions(): Promise<Array<string>>
